### ISSUE TITLE
Error when running !windex

### ISSUE THREAD

**Issue by mconnew** [rodneyviana/netext#11] opened 2020-03-02 19:58 UTC
**Describe the bug**
Attached to .NET 4.8 admin process in WinDbgX, running !windex causes the error:
```
Init was performed but it could not start CLR. Error: 8027025b
```
Using an earlier version of NetExt works as expected

**To Reproduce**
1. Install NetExt v.2.1.54.5000 into %LOCALAPPDATA%\Dbg\EngineExtensions[32]
2. Launch WinDbgX as admin
3. Attach to admin .NET 4.8 process
4. Type `.load netext`
5. Click on `!windex -tree` in netext banner text
6. Be confused by error message `Init was performed but it could not start CLR. Error: 8027025b` and open bug on github.

**Expected behavior**
I expect my process heap to be indexed

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.18363.657]
 - Browser N/A
 - Version : .NET Version 4.8.03752, WinDbgX Version 1.2001.15003.1

**Additional context**
Using 2.1.47.5000 does not exhibit the problem.

**Comment by rodneyviana** [comment] 2020-03-02 20:40
Hi Matt,

I do not have the very same versions you do, but I am using very close versions and I could not reproduce the problem.
```
0:023> .load netext
netext version 2.1.54.5000 Feb 20 2020
License and usage can be seen here: !whelp license
Check Latest version: !wupdate
For help, type !whelp (or in WinDBG run: '.browse !whelp')
Questions and Feedback: https://github.com/rodneyviana/netext/issues 
Copyright (c) 2014-2015 Rodney Viana (http://blogs.msdn.com/b/rodneyviana) 
Type: !windex -tree or ~*e!wstack to get started

0:023> !wver
Runtime(s) Found: 1
0: Filename: mscordacwks_X86_X86_4.8.4084.00.dll Location: C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscordacwks.dll
.NET Version: 4.8.4084.0
NetExt (this extension) Version: 2.1.54.5000
0:023> !windex
Starting indexing at 14:18:40 PM
Indexing finished at 14:18:44 PM
26,340,241 Bytes in 593,138 Objects
Index took 00:00:03
0:023> .chain
Extension DLL search Path:
    C:\Users\rviana\AppData\Local\dbg\UI\Fast.20200301.1\x86\WINXP(.. removed for brevity ...)
Extension DLL chain:
    netext: image 2.1.54.5000, API 1.0.0, built Thu Feb 20 17:02:32 2020
        [path: C:\Users\rviana\AppData\Local\Dbg\EngineExtensions32\netext.dll]
```

Could you please open PowerShell 32-bit and run these two lines to make sure .NET 4.8 was started?

```
Add-Type -AssemblyName System.Web;
[System.Web.Security.Membership]::GeneratePassword(15,2)
```


Then generate a full user mode manual dump file using Task Manager (or WinDbgX if you prefer). Zip the file and upload to any file service (like OneDrive) on a separated folder and ONLY share the dump file as read only and paste the link in your response and I will take a look using the very same version of .NET you have.

Meanwhile, try this: copy the 32-bit version of nextext.dll and netextshim.dll to c:\x86 (create the folder if necessary). From WinDbg or WinDbgX, load NetExt this way:

```
.load c:\x86\netext
!wver
!windex
```

Thanks,

Rodney

**Comment by rodneyviana** [comment] 2020-03-20 18:17
HI Matt,

Someone provided me a dump file with similar results for .NET 4.7.3610.0. I am researching and will reply again when I have some results.

Thanks,

Rodney

**Comment by rodneyviana** [comment] 2020-03-20 19:32
Problem should be resolved now in version 2.1.55.5000 and beyond.

**Comment by mconnew** [comment] 2020-03-20 19:49
Sorry I didn't provide a dump. I was live debugging and couldn't get it to repro again. I'm glad someone else could provide a dump which reproed.

**Comment by rodneyviana** [comment] 2020-03-24 17:50
Closing case as fix is in place. Please reopen if problem persists.

**Closed by rodneyviana** 2020-03-24 17:50 UTC
