### ISSUE TITLE
!wmodule command fails with "Init was performed but it could not start CLR. Error: 8027025b"

### ISSUE THREAD

**Issue by MikeVolodarsky** [rodneyviana/netext#17] opened 2020-11-10 19:24 UTC
Rodney, having an issue using the extension. Appreciate any points you can give.

**Describe the bug**
Attempting to use the extension's !wmodule command fails with an error:

**Init was performed but it could not start CLR. Error: 8027025b**

**To Reproduce**
1. Load the extensison

.load C:\Users\mvolo\Downloads\NetExt-2.1.58.5000\NetExt-2.1.58.5000\x64\NetExt.dll

_NetExt version 2.1.58.5000 Oct 21 2020
License and usage can be seen here: !whelp license
Check Latest version: !wupdate
For help, type !whelp (or in WinDBG run: '.browse !whelp')
Questions and Feedback: https://github.com/rodneyviana/netext/issues
Copyright (c) 2014-2015 Rodney Viana (http://blogs.msdn.com/b/rodneyviana)
Type: !windex -tree or ~*e!wstack to get started_

2. Run the !wmodule command

!wmodule -managed -noms -saveto d:\temp\dlls

_Init was performed but it could not start CLR. Error: 8027025b_

Background:
Windows 10
.NET Framework 4.8 installed

C:\Users\mvolo\Downloads\ngrok-stable-windows-amd64>filever c:\Windows\Microsoft.NET\Framework\v4.0.30319\SOS.dll
--a-- W32i   DLL ENU      4.8.4220.0 shp    767,368 07-06-2020 sos.dll

C:\Users\mvolo\Downloads\ngrok-stable-windows-amd64>filever c:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
--a-- W32i   DLL ENU      4.8.4220.0 shp  8,037,768 07-06-2020 clr.dll

0:056> !wupdate
You are up to date. Your version is 2.1.58.5000

0:056> .chain
Extension DLL search Path:
    C:\Program Files (x86)\windows kits\10\debuggers\x64\WINXP;C:\Program Files (x86)\windows kits\10\debuggers\x64\winext;C:\Program Files (x86)\windows kits\10\debuggers\x64\winext\arcade;C:\Program Files (x86)\windows kits\10\debuggers\x64\pri;C:\Program Files (x86)\windows kits\10\debuggers\x64;C:\Users\mvolo\AppData\Local\Dbg\EngineExtensions;C:\Program Files (x86)\windows kits\10\debuggers\x64;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Users\mvolo\AppData\Local\Microsoft\WindowsApps;D:\Source\Repos\Tools\tools
Extension DLL chain:
    C:\Windows\Microsoft.NET\Framework64\v4.0.30319\sos.dll: image 4.8.4220.0, API 1.0.0, built Mon Jul  6 18:45:31 2020
        [path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\sos.dll]
    C:\Users\mvolo\Downloads\NetExt-2.1.58.5000\NetExt-2.1.58.5000\x64\NetExt.dll: image 2.1.58.5000, API 1.0.0, built Wed Oct 21 13:45:19 2020
        [path: C:\Users\mvolo\Downloads\NetExt-2.1.58.5000\NetExt-2.1.58.5000\x64\NetExt.dll]
    dbghelp: image 10.0.19041.1, API 10.0.6,
        [path: C:\Program Files (x86)\windows kits\10\debuggers\x64\dbghelp.dll]
    ext: image 10.0.19041.1, API 1.0.0,
        [path: C:\Program Files (x86)\windows kits\10\debuggers\x64\winext\ext.dll]
    exts: image 10.0.19041.1, API 1.0.0,
        [path: C:\Program Files (x86)\windows kits\10\debuggers\x64\WINXP\exts.dll]
    uext: image 10.0.19041.1, API 1.0.0,
        [path: C:\Program Files (x86)\windows kits\10\debuggers\x64\winext\uext.dll]
    ntsdexts: image 10.0.19041.1, API 1.0.0,
        [path: C:\Program Files (x86)\windows kits\10\debuggers\x64\WINXP\ntsdexts.dll]

**Comment by rodneyviana** [comment] 2020-11-10 20:33
Hi Mike,

Thanks for the detailed account of the incident. It seems that .NET DAC (mscorwks) cannot be instantiated. Run this and let me know if using this command: ".cordll -u -ve -l" you are able to load mscorwks???????.dll. Also, is it a WOW6432 dump by any chance? Is it a full user mode dump?

```
.cordll -u -ve -l
```


Thanks,

Rodney

**Comment by MikeVolodarsky** [comment] 2020-11-10 21:59
Hey Rodney, 

Former MSFTy here, familiar with the expected/actual/repro steps :) 

Thank you for the awesomely fast response! 

Here is the result:

0:043> .cordll -u -ve -l
CLRDLL: Loaded DLL C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscordacwks.dll
Automatically loaded SOS Extension
CLR DLL status: Loaded DLL C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscordacwks.dll

After this, running !wmodule:

0:043> !wmodule -managed -noms -saveto d:\temp\dlls
e0434352 Exception in C:\Users\mvolo\Downloads\NetExt-2.1.58.5000\NetExt-2.1.58.5000\x64\NetExt.dll.wmodule debugger extension.
      PC: 00007fff`4d993b29  VA: 00000000`00000000  R/W: 80004003  Parameter: 00000000`00000000

--

This is in a live debug session on a 64bit Win10, 64bit w3wp.exe. Confirmed all system dlls loading from c:\windows\system32\inetsrv not syswow64.

Let me know your thoughts.

**Comment by rodneyviana** [comment] 2020-11-10 22:19
Hi Mike,

I was able to reproduce. It only fails on live targets. I will troubleshoot and will let you know the results. Meanwhile, if you save a dump of the process you will be able to extract your modules. Try this workaround until I get it sorted out.

**Comment by MikeVolodarsky** [comment] 2020-11-10 22:24
Rodney, thanks much for this workaround. 

I tried on a minidump, and confirm it worked!

We are able to move forward via the dump route, so this unblocks us. Appreciate your help. Should I keep this issue open to track a fix for live module export? If not in the cards I can close it.

**Comment by rodneyviana** [comment] 2020-11-10 22:33
Let's keep it open. The problem is that I am not treating live target memory mapping correctly.

**Comment by MikeVolodarsky** [comment] 2020-11-10 23:46
Ok, thank you. We'll be using this extension more going forward and if there are any other issues, will bring them up.


Thanks for putting this together!


Best,
Mike

--- original message ---
On November 10, 2020, 5:33 PM EST notifications@github.com wrote:



Let's keep it open. The problem is that I am not treating live target memory mapping correctly.

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by rodneyviana** [comment] 2020-11-11 05:36
Hi Mike,

The new version should be ok. Would be so kind as to test it? Keep me informed of what you are doing with the extension and let me know if you need help.

**Comment by MikeVolodarsky** [comment] 2020-11-11 16:20
Hey Rodney,

Great work! Confirm the latest version NetExt-2.1.59.5000 now works in these cases:

1. Live 64 bit w3wp
2. .dump /ma of same process

Just in case I did a quick windiff of DLLs exported yesterday with the other version, the new version live, and new version dump, and they all match.

Thanks again for the quick fix. Looking forward to using the extension further.

If we have additional feedback or questions, do you have a contact route other than bug reports you may be willing to share? You can reach me at mike@leansentry.com.

Best,
Mike

**Comment by rodneyviana** [comment] 2020-11-11 21:31
Thanks for the feedback. I am closing this issue and considering it resolved.

**Closed** 2020-11-12 17:07 UTC
