### ISSUE TITLE
Values of the Dictionary Entries

### ISSUE THREAD

**Issue by jerzy-d** [rodneyviana/netext#2] opened 2018-01-13 13:54 UTC
First, thank you for this WinDbg extention.
We processing a lot of crash dumps of our clients and your stuff is heaven-sent.

DISCLAIMER: The crash dump is of my test app with target .NET Framework 4.7.1 ...maybe NetExt does not support that yet.
            If this is the case please disregard.
            
In the crash dump I have instance of:
Dictionary<KeyValuePair<string, int>, KeyValuePair<string, int>>
It's keys and values are:
**("kvDictKey0", 0) -> ("kvDictVal0", 0)
("kvDictKey1", 1) -> ("kvDictVal1", 1)
("kvDictKey2", 2) -> ("kvDictVal2", 2)**
So we have Entry struct containing other struct types.
Below is output from NetExt, it looks like I cannot get to the inner values of the dictionary entries.
When I click on the -mt entry an exception is thrown.
_0:000> !wdict 0x0001521d577590
Items   : 3
[0]:==============================================(Physical Index: 2)
System.Collections.Generic.KeyValuePair key = -mt 00007FFDF2881DC8 000001521D577768
System.Collections.Generic.KeyValuePair value = -mt 00007FFDF2881DC8 000001521D577778
[1]:==============================================(Physical Index: 1)
System.Collections.Generic.KeyValuePair key = -mt 00007FFDF2881DC8 000001521D577740
System.Collections.Generic.KeyValuePair value = -mt 00007FFDF2881DC8 000001521D577750
[2]:==============================================(Physical Index: 0)
System.Collections.Generic.KeyValuePair key = -mt 00007FFDF2881DC8 000001521D577718
System.Collections.Generic.KeyValuePair value = -mt 00007FFDF2881DC8 000001521D577728
0:000> !wselect mt 140728672460232 * from 000001521d577768
c0000005 Exception in netext.wselect debugger extension.
      PC: 00007ffd`f76b6ba2  VA: 00000000`00000000  R/W: 0  Parameter: ffff8287`3a8ca8b4
0:000> !wselect mt 140728672460232 * from 000001521d577778
c0000005 Exception in netext.wselect debugger extension.
      PC: 00007ffd`f76b6ba2  VA: 00000000`00000000  R/W: 0  Parameter: ffff8287`3a8ca8b4_

**Comment by rodneyviana** [comment] 2018-02-02 00:36
I fixed it in 2.1.18.500. Please let me know if it works for you now.

**Comment by jerzy-d** [comment] 2018-02-03 22:20
I am sorry say that it is not. See below.
I would give you more info, but I cannot compile .NetExt on my machine and see in debugger what's happening. 
If you care to test it yourself I put this crash dump in:
**https://github.com/jerzy-d/MDRDesk/releases/download/v1.0-test.0/TestApp.exe_180126_201106.zip**
_0:000> !wdict 0x0001ab80007718
Items   : 3
[0]:==============================================(Physical Index: 2)
System.Collections.Generic.KeyValuePair key = -mt 00007FFDF4111DC8 000001AB800078F0
System.Collections.Generic.KeyValuePair value = -mt 00007FFDF4111DC8 000001AB80007900
[1]:==============================================(Physical Index: 1)
System.Collections.Generic.KeyValuePair key = -mt 00007FFDF4111DC8 000001AB800078C8
System.Collections.Generic.KeyValuePair value = -mt 00007FFDF4111DC8 000001AB800078D8
[2]:==============================================(Physical Index: 0)
System.Collections.Generic.KeyValuePair key = -mt 00007FFDF4111DC8 000001AB800078A0
System.Collections.Generic.KeyValuePair value = -mt 00007FFDF4111DC8 000001AB800078B0
0:000> !wselect mt f4111dc8 * from 800078f0
c0000005 Exception in netext.wselect debugger extension.
      PC: 00007ffe`01827142  VA: 00000000`00000000  R/W: 0  Parameter: ffff8287`3a2ae8b4
0:000> !wupdate
You are up to date. Your version is 2.1.18.5100_

**Comment by rodneyviana** [comment] 2018-02-06 21:23
Hi jerzy-d. I downloaded the dump.

It is a bug in !wselect. The command is cutting the address to 32-bits.
So instead of showing:
0:000> !wselect mt 00007FFDF4111DC8 * from 000001AB800078F0
[System.Collections.Generic.KeyValuePair<System.__Canon,System.Int32>]
System.__Canon key = 000001ab800032e8 kvDictKey2
(int32)System.Int32 value = 2 (0n2)

It is showing:
0:000> !wselect mt f4111dc8 * from 800078f0
c0000005 Exception in netext.wselect debugger extension.
      PC: 00007ffa`889d7142  VA: 00000000`00000000  R/W: 0  Parameter: ffffcb0a`14888080

I will fix it and when you see any version over 2.1.18.5100, the problem is resolved.

Thanks for bringing it up.

**Comment by rodneyviana** [comment] 2018-02-06 23:36
0:000> !wver
Runtime(s) Found: 1
0: Filename: mscordacwks_Amd64_Amd64_4.7.2600.00.dll 
.NET Version: 4.7.2600.0
NetExt (this extension) Version: 2.1.19.5000


0:000> !wdict 0x0001ab80007718
Items   : 3
[0]:==============================================(Physical Index: 2)
System.Collections.Generic.KeyValuePair key = -mt 00007FFDF4111DC8 000001AB800078F0
System.Collections.Generic.KeyValuePair value = -mt 00007FFDF4111DC8 000001AB80007900
[1]:==============================================(Physical Index: 1)
System.Collections.Generic.KeyValuePair key = -mt 00007FFDF4111DC8 000001AB800078C8
System.Collections.Generic.KeyValuePair value = -mt 00007FFDF4111DC8 000001AB800078D8
[2]:==============================================(Physical Index: 0)
System.Collections.Generic.KeyValuePair key = -mt 00007FFDF4111DC8 000001AB800078A0
System.Collections.Generic.KeyValuePair value = -mt 00007FFDF4111DC8 000001AB800078B0
0:000> !wselect mt 00007ffdf4111dc8 * from 000001ab800078f0
[System.Collections.Generic.KeyValuePair<System.__Canon,System.Int32>]
System.__Canon key = 000001ab800032e8 kvDictKey2 kvDictKey2
(int32)System.Int32 value = 2 (0n2)

**Comment by jerzy-d** [comment] 2018-02-07 03:05
Confirmed! Thank you.
Should I close this issue or you do? I'm new to GitHub, don't know the rules of etiquette.

**Comment by rodneyviana** [comment] 2018-02-19 02:30
Thanks for confirming. I will close the issue now.

**Closed by rodneyviana** 2018-02-19 02:30 UTC
